### ISSUE TITLE
Feature request: Round pot stacks

### ISSUE THREAD

**Issue by Naktibalda** [rafanoronha/scala-poker#45]
Currently StackManagement keeps a total better's contribution to the pot.

It is convenient for calculating side pots, so I want to keep this functionality,
but it is very inconvenient for calculating Call and Raise amounts,
it would be much better if we kept an amount that the better bet in the current round separately.

I really need this for a BettingRound.placeRaise function - it has incorrect calculation now.

**Comment by rafanoronha** [comment]
Absolutely, go ahead :+1:

**Comment by Naktibalda** [comment]
I has been thinking about this issue.

My idea is that the chips should move from players stacks to table stacks when betting,
at the end of the round all table stacks are passed to PotManager,
which calculates the main pot and side pots and keeps track what players contributes to the side pots.

**Comment by Naktibalda** [comment]
I will try it implement it my way, it is up to you to accept it or do it your way.

**Comment by rafanoronha** [comment]
@Naktibalda feel free to submit your code.
sorry for not coming with something yet, I'm all messed up
